version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo "Listing all files:"
      - ls -al
      - echo "Checking eval/docker directory:"
      - ls -al eval/docker 
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG -f eval/docker/dockerfile .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
      
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"eval-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo Running ECS task...
      - aws ecs list-task-definitions --family-prefix EvalSandboxECS --sort DESC --max-items 1 --query 'taskDefinitionArns[0]' --output text
      - echo "Command Output: $?"
      - export TASK_DEFINITION=$(aws ecs list-task-definitions --family-prefix EvalSandboxECS --sort DESC --max-items 1 --query 'taskDefinitionArns[0]' --output text)
      - echo "Task Definition"
      - echo $TASK_DEFINITION
      - aws ecs run-task --cluster eval-cluster --task-definition $TASK_DEFINITION --launch-type FARGATE --network-configuration "awsvpcConfiguration={subnets=[$(aws ec2 describe-subnets --filters Name=vpc-id,Values=$(aws ecs describe-clusters --clusters eval-cluster --query 'clusters[0].vpcId' --output text) --query 'Subnets[0].SubnetId' --output text)],assignPublicIp=ENABLED}"
      - echo Waiting for task to complete...
      - sleep 60  # 等待任务完成，根据实际情况调整等待时间

artifacts:
  files:
    - imagedefinitions.json
