name: Deploy Dev

on:
  push:
    branches:
      - main
    paths:
      - 'aws-resources/**'
      - '.github/workflows/**'

permissions:
  actions: read
  contents: read
  id-token: write
  packages: read

jobs:
  call-deploy-aws-resources:
    uses: ./.github/workflows/deploy-aws-resources.yml
    secrets: inherit
    with:
      environment: "dev"